"""
Term of the Day: one ENR concept per weekday, explained for a first-year analyst.
Add your own at the end. Each entry is (term, what it is, why it matters).
"""

TERMS = [
    ("WTI vs Brent",
     "Two benchmark oil prices. WTI (West Texas Intermediate) is US oil priced at Cushing, Oklahoma; Brent is North Sea oil and the global benchmark.",
     "Most of the world's oil is priced off Brent, so a wider Brent-WTI gap usually means global supply is tighter than US supply."),
    ("WCS differential",
     "The discount of Western Canadian Select (heavy oil from the oil sands) versus WTI.",
     "Canadian producers like Suncor, CNQ and Cenovus get paid closer to WCS than WTI. A narrower discount (thanks to new pipelines like Trans Mountain) means more money for them."),
    ("Crack spread",
     "The profit a refiner makes turning a barrel of crude into gasoline and diesel: product prices minus the crude price.",
     "It's the key number for refiners and integrated companies like Suncor and Cenovus. High crack spreads mean fat refining margins."),
    ("Contango and backwardation",
     "Contango: future oil prices are higher than today's. Backwardation: future prices are lower than today's.",
     "Backwardation usually means the market is tight right now (buyers need oil today). Contango usually means there's too much supply and storage is filling up."),
    ("OPEC+",
     "OPEC (Saudi Arabia and other major exporters) plus allies like Russia. Together they control a large share of world oil output.",
     "When OPEC+ cuts production, prices tend to rise; when it adds barrels, prices tend to fall. Their meetings are big events for every oil stock."),
    ("Henry Hub",
     "The main US natural gas price, set at a pipeline hub in Louisiana and quoted in $/MMBtu (a unit of heat energy).",
     "It's the gas price in the brief's commodity table. It drives gas producers' revenue and the fuel cost for power companies like NRG."),
    ("LNG",
     "Liquefied natural gas: gas cooled to -162°C so it can be shipped by tanker overseas.",
     "LNG exports link cheap North American gas to higher prices in Europe and Asia. New LNG terminals (like LNG Canada) can lift local gas prices."),
    ("Upstream, midstream, downstream",
     "Upstream finds and produces oil and gas (E&Ps). Midstream moves and stores it (pipelines like Enbridge). Downstream refines and sells it (refiners, gas stations).",
     "Each reacts differently to oil prices. Upstream swings the most with oil, midstream earns steadier fee-based income, and downstream cares about crack spreads."),
    ("E&P",
     "Exploration and production company: a business that only finds and pumps oil and gas (e.g. ConocoPhillips, Occidental).",
     "E&P stocks are the most sensitive to oil and gas prices. The XOP ETF in your brief tracks them."),
    ("Breakeven price",
     "The oil price a company needs to cover its costs (and often its dividend).",
     "Low-breakeven producers stay profitable when oil falls. Analysts compare breakevens to judge who survives a downturn."),
    ("Rig count",
     "The weekly count (from Baker Hughes) of drilling rigs operating in the US and Canada.",
     "More rigs today usually means more production in 6-12 months, which can weigh on prices later."),
    ("EIA inventory report",
     "The US Energy Information Administration's weekly report (Wednesdays) on how much crude, gasoline and diesel is in storage.",
     "A bigger-than-expected build in inventories is bearish for prices; a bigger draw is bullish. Oil often moves sharply right after it comes out."),
    ("Strategic Petroleum Reserve (SPR)",
     "The US government's emergency oil stockpile, stored in underground salt caverns.",
     "Releasing SPR oil adds supply and can push prices down; refilling it adds demand."),
    ("Spot vs futures price",
     "Spot is the price for delivery now. A futures price is agreed today for delivery at a set date later.",
     "The commodity prices in your brief are front-month futures, which is how most commodities are quoted and traded."),
    ("Hedging",
     "Locking in a future selling price (with futures or swaps) to reduce uncertainty.",
     "A heavily hedged producer won't fully benefit from a price spike, but is protected in a crash. Check hedge books in quarterly reports."),
    ("Free cash flow (FCF)",
     "Cash from operations minus capital spending: the cash left over after keeping the business running and growing.",
     "Energy investors focus on FCF because it pays dividends and buybacks. FCF yield (FCF / market cap) is a common valuation check."),
    ("Capex",
     "Capital expenditures: money spent on long-term assets like wells, mines, pipelines and power plants.",
     "Capex guidance tells you how much a company plans to grow. Cutting capex often boosts FCF in the short term."),
    ("EBITDA",
     "Earnings before interest, taxes, depreciation and amortization: a rough measure of operating cash profit.",
     "It lets you compare companies with different debt levels and asset ages. It's widely used for capital-heavy ENR businesses."),
    ("EV/EBITDA",
     "Enterprise value (market cap + debt - cash) divided by EBITDA.",
     "It's the go-to valuation multiple in energy and mining. Lower can mean cheaper, but compare against close peers only."),
    ("Netback",
     "The profit per barrel after royalties, production costs and transport: price minus all per-barrel costs.",
     "It's a key Canadian oil metric. Higher netbacks mean more profitable barrels."),
    ("Reserves (1P / 2P)",
     "Estimated oil, gas or minerals a company can economically produce. 1P = proved; 2P = proved + probable.",
     "Reserves are the inventory of the business. Reserve life (reserves / annual production) shows how long it can keep producing."),
    ("Dividend yield and payout ratio",
     "Yield = annual dividend / share price. Payout ratio = dividends / earnings (or FCF).",
     "Many ENR stocks (pipelines, majors) are owned for income. A very high payout ratio can mean the dividend is at risk."),
    ("AISC",
     "All-in sustaining cost: what it costs a gold miner to produce one ounce, including upkeep capex.",
     "The gold price minus AISC is the miner's margin. With gold high, low-AISC miners like Agnico Eagle earn big margins."),
    ("Ore grade",
     "How much metal is in each tonne of rock (e.g. grams of gold per tonne, or % copper).",
     "Higher grade means more metal for the same mining cost. It's one of the biggest drivers of a mine's profitability."),
    ("Royalty and streaming companies",
     "Firms that fund mines up front in exchange for a cut of future production (e.g. Franco-Nevada, Wheaton Precious Metals).",
     "They get commodity exposure with less cost risk than miners, so they often trade at premium multiples."),
    ("Rare earth elements",
     "17 metals used in magnets, electronics and defense tech. Neodymium (Nd) and praseodymium (Pr) are the most valuable for magnets.",
     "They're core to MP Materials. China dominates mining and especially processing, so its policy moves prices."),
    ("NdPr oxide",
     "A mixed neodymium-praseodymium powder, the main product sold by rare earth miners, priced in $/kg.",
     "NdPr goes into the permanent magnets used in EV motors, wind turbines and missiles. It's MP Materials' main revenue driver."),
    ("Permanent magnets",
     "Strong magnets (NdFeB) made from NdPr, iron and boron.",
     "Most are made in China. MP Materials is building US magnet production, which is why defense and auto deals matter so much for the stock."),
    ("Critical minerals",
     "Minerals that governments consider vital to the economy and national security and whose supply is at risk (rare earths, lithium, cobalt, graphite and others).",
     "Government policies (funding, price floors, export bans) can move these stocks more than normal supply and demand."),
    ("Price floor",
     "A guaranteed minimum price. If the market price drops below it, the buyer (often a government) pays the difference.",
     "MP's US Defense Department deal includes an NdPr price floor, which reduces downside risk to its revenue."),
    ("Export controls",
     "Government limits on selling certain goods abroad.",
     "When China restricts rare earth or magnet exports, prices outside China and Western producers like MP and Lynas often jump."),
    ("Offtake agreement",
     "A deal where a buyer agrees in advance to purchase a share of a mine's or plant's future output.",
     "Offtakes from big names (automakers, Apple, governments) de-risk new projects and help them get financing."),
    ("Dr. Copper",
     "A nickname for copper because its price is seen as a signal of global economic health.",
     "Copper is used in construction, electronics, EVs and the power grid. Rising copper often points to stronger growth expectations."),
    ("Uranium spot vs term price",
     "Spot is the price for near-term delivery. Term is the price in long-term contracts utilities sign with miners.",
     "Most uranium sells on term contracts, so Cameco's revenue follows the term price more than the headline spot price."),
    ("Independent power producer (IPP)",
     "A company that owns power plants and sells electricity at market prices (NRG, Vistra, Constellation), unlike a regulated utility with set rates.",
     "IPPs earn more when power prices rise, so they move more than regular utilities. That's why NRG can jump 7% in a day."),
    ("ERCOT",
     "The grid operator for most of Texas, which runs its own largely unregulated power market.",
     "NRG and Vistra have big Texas businesses. Heat waves and cold snaps in ERCOT can spike power prices and their profits."),
    ("Capacity market",
     "An auction where grid operators (like PJM in the US Northeast and Midwest) pay power plants to be available in future years.",
     "High capacity auction prices are a direct profit boost for plant owners like NRG and Constellation."),
    ("Spark spread",
     "The gross margin of a gas-fired power plant: the power price minus the cost of the gas needed to make it.",
     "It's the key profitability metric for gas-heavy generators like NRG. Higher power prices or cheaper gas widen it."),
    ("Baseload vs peaker plants",
     "Baseload plants (nuclear, large gas) run nearly all the time. Peakers switch on only when demand spikes.",
     "Peakers earn most of their money in a few extreme hours, which makes IPP profits sensitive to weather."),
    ("Power purchase agreement (PPA)",
     "A long-term contract to buy electricity from a specific generator at an agreed price.",
     "Data centers signing PPAs with nuclear or gas plants (like Google with Constellation) lock in long-term revenue for power producers."),
    ("Data center power demand",
     "The fast-growing electricity use of AI and cloud data centers.",
     "It's one of the biggest themes behind the rally in power stocks like NRG, Vistra and Constellation, since US power demand was flat for years."),
    ("Basis points (bps)",
     "One hundredth of a percentage point: 0.25% = 25 bps.",
     "Rates and yields are quoted in bps. A 25 bps rate cut by the Fed or Bank of Canada is a standard move."),
    ("The 10-year yield",
     "The interest rate on 10-year US government bonds, the benchmark for long-term borrowing costs.",
     "Higher yields make dividend stocks like utilities and pipelines less attractive and raise their borrowing costs, so they often fall when yields jump."),
    ("VIX",
     "The 'fear gauge': the market's expected S&P 500 volatility over the next 30 days.",
     "Below about 15 is calm and above about 25 is stressed. Spikes usually come with selloffs."),
    ("USD/CAD",
     "How many Canadian dollars one US dollar buys.",
     "Oil is priced in USD but Canadian producers pay costs in CAD, so a weaker loonie (higher USD/CAD) boosts their profits."),
    ("Beta",
     "How much a stock tends to move relative to the overall market. A beta of 1.5 moves about 1.5x the market.",
     "Miners and E&Ps often have high betas; pipelines and utilities usually have low betas."),
    ("52-week range",
     "The lowest and highest prices a stock hit over the past year.",
     "Where a stock sits in that range shows momentum at a glance. Your brief shows it as a percentage (0% = at the low, 100% = at the high)."),
    ("ETF",
     "Exchange-traded fund: a basket of stocks that trades like a single stock.",
     "Sector ETFs (XLE, XME, REMX) are the fastest way to see how a whole sub-sector did, separate from one company's news."),
]


def term_for(day_index):
    return TERMS[day_index % len(TERMS)]
